---
default_language_version:
  python: python3
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [python]
        args: [--fix, --exit-non-zero-on-fix]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: nbqa-ruff
        name: nbqa ruff
        entry: nbqa ruff
        language: system
        args: [--fix, --exit-non-zero-on-fix]
        files: \.ipynb$
      - id: nbqa-black
        name: nbqa black
        entry: nbqa black
        language: system
        files: \.ipynb$
      - id: nbconvert
        name: nbconvert
        entry: jupyter nbconvert
        args: [--clear-output, --inplace]
        language: system
        files: \.ipynb$
